version: '3.9'

services:
  seguros-autos-microservice:
    build: /home/seu-usuario/corebankingmicroservices-cleanarch-2/seguros-autos-microservice/
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_EXCHANGE=direct_exchange_seguros
      - RABBITMQ_QUEUE=fila_seguros
      - RABBITMQ_ROUTING_KEY=seguro_key
      - DYNAMODB_ACCESS_KEY_ID=fakeAccessKey
      - DYNAMODB_SECRET_ACCESS_KEY=fakeSecretKey
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8001
    ports:
      - "8020:8020"
    networks:
      - microservice-network
    depends_on:
      - dynamodb
      - redis-cache
      - rabbitmq
      - prometheus
      - grafana

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8001:8000"
    networks:
      - microservice-network

  redis-cache:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - microservice-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus4
    ports:
      - "9096:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana
    container_name: grafana4
    ports:
      - "3088:3000"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  dynamodb_data:
